date_format = "%Y-%m-%d %a"

[output]
file = "ledger_dat"
format.locale = "en_US.UTF-8"
format.indentation = 4 # Number of spaces each posting should be indented by
format.margin = 8 # Number of spaces between the end of the destination/source
		  # account and the beginning of the amount

[[accounts]]
identifier = "XXXXXXXXXXXXXXX1"
ledger_source = "Assets:Chequing"

date_column = 1
date_format = "%m/%d/%Y"
debit_column = 5
debit_format = "{:.2f}"
credit_column = 5
credit_format = "{:.2f}"
payee_columns = [3, 4]

display_columns = [1, 5, 3, 4]

[[accounts]]
identifier = "XXXXXXXXXXXXXXX2"
ledger_source = "Liabilities:Credit Card"

date_column = 2
date_format = "%Y%m%d"
debit_column = 4
debit_format = "{:.2f}"
credit_column = 4
credit_format = "{:.2f}"
payee_columns = [5]

display_columns = [2, 4, 5]
